name: SSH Login

on:
  schedule:
    - cron: '0 1 1 * *'  # 每月的 1号 北京时间 01 点运行
  workflow_dispatch:

jobs:
  ssh-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paramiko requests


      - name: Run Python script
        env:
          SSH_INFO: ${{ secrets.SSH_INFO }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          DD_BOT_ACCESS_TOKEN: ${{ secrets.DD_BOT_ACCESS_TOKEN }}
        run: python login.py